[package]
name = "dmxdotblog"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
rocket = "0.5.1"
serde = "1.0.210"

[dependencies.rocket_dyn_templates]
version = "0.2.0"
features = ["tera"] 
